/**
 * Skone Remote Support Agent - Runs on USER's computer
 * Downloaded and launched by the BAT script the user gets from the server.
 *
 * Environment variables set by the BAT launcher:
 *   SKONE_SERVER  - URL of the Skone Remote Support server
 *   SKONE_CODE    - 6-char connection code generated by admin
 */

const { io } = require('socket.io-client');
const screenshot = require('screenshot-desktop');
const { mouse, keyboard, Button, Key, screen } = require('@nut-tree-fork/nut-js');
const path = require('path');

// --- Configuration ---
const SERVER_URL = process.env.SKONE_SERVER || process.env.REMOTEDESK_URL || 'http://localhost:3000';
const SKONE_CODE = (process.env.SKONE_CODE || process.argv[2] || '').toUpperCase();
const FRAME_INTERVAL_MS = parseInt(process.env.SKONE_FPS_MS) || 100; // 100ms = 10 FPS

if (!SKONE_CODE) {
  console.error('\n❌ No connection code provided.');
  console.error('   Set SKONE_CODE env var or pass code as argument: node agent.js ABCDEF\n');
  process.exit(1);
}

// Configure nut-js for fast operations
mouse.config.autoDelayMs = 0;
keyboard.config.autoDelayMs = 0;

// --- Connect to server ---
const socket = io(SERVER_URL);
let sessionId = null;
let isAdminConnected = false;
let captureLoop = null;

console.log('\n🖥️  Skone Remote Support Agent Starting...');
console.log(`📡 Server  : ${SERVER_URL}`);
console.log(`🔑 Code    : ${SKONE_CODE}\n`);

// --- Socket Event Handlers ---

socket.on('connect', () => {
  console.log(`✅ Connected to server (socket: ${socket.id})`);
  console.log('📋 Registering with connection code...\n');
  socket.emit('agent:register', { code: SKONE_CODE });
});

socket.on('agent:registered', ({ sessionId: id }) => {
  sessionId = id;
  console.log('══════════════════════════════════════════════');
  console.log('  ✅ Connected! Waiting for admin to join...');
  console.log('══════════════════════════════════════════════\n');
});

socket.on('agent:error', ({ message }) => {
  console.error(`\n❌ Server error: ${message}`);
  console.error('   Make sure the connection code is valid and not expired.\n');
  process.exit(1);
});

socket.on('agent:admin-connected', () => {
  console.log('👤 Admin connected! Starting screen capture...');
  isAdminConnected = true;
  socket.emit('agent:ready');
  startCapture();
});

socket.on('agent:admin-disconnected', () => {
  console.log('👤 Admin disconnected. Pausing capture...');
  isAdminConnected = false;
  stopCapture();
});

socket.on('agent:capture-frame', async () => {
  if (!isAdminConnected) return;
  await captureAndSend();
});

// --- Mouse Control Handlers ---

socket.on('agent:mousemove', async ({ x, y, screenW, screenH }) => {
  try {
    const screenSize = await screen.width();
    const actualScreenH = await screen.height();
    // Scale from admin's canvas coords to actual screen coords
    const actualX = Math.round((x / screenW) * screenSize);
    const actualY = Math.round((y / screenH) * actualScreenH);
    await mouse.setPosition({ x: actualX, y: actualY });
  } catch (e) {
    // Silently ignore move errors to keep stream smooth
  }
});

socket.on('agent:mouseclick', async ({ x, y, screenW, screenH, button }) => {
  try {
    const screenW_actual = await screen.width();
    const screenH_actual = await screen.height();
    const actualX = Math.round((x / screenW) * screenW_actual);
    const actualY = Math.round((y / screenH) * screenH_actual);
    await mouse.setPosition({ x: actualX, y: actualY });
    const btn = button === 'right' ? Button.RIGHT : Button.LEFT;
    await mouse.click(btn);
    console.log(`🖱️  Click at (${actualX}, ${actualY}) [${button || 'left'}]`);
  } catch (e) {
    console.error('Click error:', e.message);
  }
});

socket.on('agent:rightclick', async ({ x, y, screenW, screenH }) => {
  try {
    const screenW_actual = await screen.width();
    const screenH_actual = await screen.height();
    const actualX = Math.round((x / screenW) * screenW_actual);
    const actualY = Math.round((y / screenH) * screenH_actual);
    await mouse.setPosition({ x: actualX, y: actualY });
    await mouse.click(Button.RIGHT);
    console.log(`🖱️  Right-click at (${actualX}, ${actualY})`);
  } catch (e) {
    console.error('Right-click error:', e.message);
  }
});

socket.on('agent:scroll', async ({ deltaY }) => {
  try {
    if (deltaY > 0) {
      await mouse.scrollDown(3);
    } else {
      await mouse.scrollUp(3);
    }
  } catch (e) {
    console.error('Scroll error:', e.message);
  }
});

// --- Keyboard Control Handler ---

// Map of common key names to nut-js Key enum
const keyMap = {
  'Enter': Key.Return,
  'Backspace': Key.Backspace,
  'Delete': Key.Delete,
  'Escape': Key.Escape,
  'Tab': Key.Tab,
  'ArrowUp': Key.Up,
  'ArrowDown': Key.Down,
  'ArrowLeft': Key.Left,
  'ArrowRight': Key.Right,
  'Home': Key.Home,
  'End': Key.End,
  'PageUp': Key.PageUp,
  'PageDown': Key.PageDown,
  'F1': Key.F1, 'F2': Key.F2, 'F3': Key.F3, 'F4': Key.F4,
  'F5': Key.F5, 'F6': Key.F6, 'F7': Key.F7, 'F8': Key.F8,
  'F9': Key.F9, 'F10': Key.F10, 'F11': Key.F11, 'F12': Key.F12,
  'Control': Key.LeftControl, 'Alt': Key.LeftAlt, 'Shift': Key.LeftShift,
  'Meta': Key.LeftSuper, 'Space': Key.Space,
  ' ': Key.Space,
};

socket.on('agent:keypress', async ({ key, code, ctrlKey, altKey, shiftKey }) => {
  try {
    const keysToPress = [];

    // Add modifier keys
    if (ctrlKey) keysToPress.push(Key.LeftControl);
    if (altKey) keysToPress.push(Key.LeftAlt);
    if (shiftKey) keysToPress.push(Key.LeftShift);

    // Find the main key
    let mainKey = keyMap[key];
    if (!mainKey && key && key.length === 1) {
      // For printable characters, use type() instead
      await keyboard.type(key);
      console.log(`⌨️  Type: "${key}"`);
      return;
    }

    if (mainKey) {
      keysToPress.push(mainKey);
      await keyboard.pressKey(...keysToPress);
      await keyboard.releaseKey(...keysToPress);
      console.log(`⌨️  Key: ${key} ${ctrlKey ? '[Ctrl]' : ''} ${altKey ? '[Alt]' : ''} ${shiftKey ? '[Shift]' : ''}`);
    }
  } catch (e) {
    console.error('Key error:', e.message);
  }
});

// --- Screen Capture ---

async function captureAndSend() {
  if (!isAdminConnected) return;
  try {
    const imgBuffer = await screenshot({ format: 'jpeg' });
    const base64 = imgBuffer.toString('base64');
    socket.emit('agent:frame', { data: base64, timestamp: Date.now() });
  } catch (e) {
    console.error('Capture error:', e.message);
  }
}

function startCapture() {
  if (captureLoop) return;
  captureLoop = setInterval(captureAndSend, FRAME_INTERVAL_MS);
}

function stopCapture() {
  if (captureLoop) {
    clearInterval(captureLoop);
    captureLoop = null;
  }
}

// --- Disconnect / Error Handling ---

socket.on('disconnect', () => {
  console.log('\n❌ Disconnected from server. Reconnecting...');
  stopCapture();
  isAdminConnected = false;
});

socket.on('connect_error', (err) => {
  console.error(`Connection error: ${err.message}`);
});

process.on('SIGINT', () => {
  console.log('\n👋 Agent shutting down...');
  stopCapture();
  socket.disconnect();
  process.exit(0);
});
